Repository Skrishna0703/Food-Del, pull requests merged in 2025-08, with the labels that each got.

#58 Make Navbar Responsive and Auto-Close Mobile Menu on Link Click
  frontend/src/Componets/Header/Header.css
  frontend/src/Componets/Navbar/Navbar.css
  frontend/src/Componets/Navbar/Navbar.jsx
  frontend/src/Componets/ThemeToggle.jsx
Labels: GSSOC 25, level 1

#53 Updated Navbar styles and added glass effect
  frontend/src/Componets/Header/Header.css
  frontend/src/Componets/Navbar/Navbar.css
  frontend/src/Componets/Navbar/Navbar.jsx
  frontend/src/Componets/ThemeToggle.jsx
Labels: GSSOC 25, level 1

#57 Issue #7 fixed
  frontend/src/Componets/ExploreMenu/ExploreMenu.css
  frontend/src/Componets/FoodDisplay/FoodDisplay.css
  frontend/src/Componets/FoodItem/FoodItem.css
  frontend/src/Componets/Header/Header.css
  frontend/src/Componets/Header/Header.jsx
  frontend/src/Componets/Navbar/Navbar.css
  frontend/src/Componets/Navbar/Navbar.jsx
Labels: GSSOC 25, Level 1

#75 Added favorites option
  frontend/src/Componets/FoodDisplay/FoodDisplay.css
  frontend/src/Componets/FoodDisplay/FoodDisplay.jsx
Labels: GSSOC 25, Level 2

#78 Fixed the uneven review card sizes & added avator icon on review cards
  frontend/src/Componets/CustomerReview/CustomerReviews.css
  frontend/src/Componets/CustomerReview/CustomerReviews.jsx
  frontend/src/Componets/Navbar/Navbar.jsx
  package-lock.json
Labels: enhancement, GSSOC 25, Level 1

#114 Implemented Client-Side Food Recommendation System for Tomato App
  frontend/src/Componets/FoodDisplay/FoodDisplay.jsx
  frontend/src/Componets/FoodItem/FoodItem.jsx
  frontend/src/Componets/FoodRecommendations/FoodRecommendations.css
  frontend/src/Componets/FoodRecommendations/FoodRecommendations.jsx
  frontend/src/Context/StoreContext.jsx
  frontend/src/Pages/Home/Home.jsx
Labels: GSSOC 25, Level 2

#120 Redesign Scroll Navigation Button with Correct Direction Indicators
  frontend/src/App.jsx
  frontend/src/Componets/ScrollToTop.jsx
Labels: GSSOC 25, Level 1

#121 Fixed : Enhancement of Tomato Logo Hover Effect in Navbar
  frontend/src/Componets/Navbar/Navbar.css
Labels: GSSOC 25, Level 1
